### ISSUE TITLE
test don't support Masonry?

### ISSUE THREAD

**Issue by LinkRober** [facebookarchive/ios-snapshot-test-case#168]
I mean that it don't support Masonry?

**Comment by Grubas7** [comment]
It does. Masonry it's basically extra layer for NSLayoutConstraints.
What kind of problem you have. Write something more, or upload some sample.

**Comment by nscoding** [comment]
Can you upload a sample project as @Grubas7 suggested? This will helps us track this down

**Comment by LinkRober** [comment]
thx

**Comment by Grubas7** [comment]
Close this issue?
