### ISSUE TITLE
Any way we can use this with XC UI Tests.?

### ISSUE THREAD

**Issue by sukesh1989** [facebookarchive/ios-snapshot-test-case#217]
Any way we can use this with XC UI Tests.? I want to compare screenshots of app and determine the video rendering and player features. Can you please help? Can i pass XCUIELEMENT or XCUIAPPLICATION objects somehow?

**Comment by Grubas7** [comment]
Unit tests and UI tests inherits files from `XCTestCase`. Same as `FBSnapshotTestCase` so you should be able to take a snapshot in your UI test.

**Comment by alextakahashi** [comment]
I was trying to implement `FBSnapshotTestCase` with my UITests, but I couldn't generate a view / layer from the `XCUIApplication`.  If I could simply get a snapshot of the simulator that would be great.

I haven't had a ton of experience working with `XCUIElement`.  I'd really appreciate any help!

**Comment by acecilia** [comment]
See: https://medium.com/@joesusnick/snapshot-xcui-testing-6a16c7ccd47b for a implementation example
