### ISSUE TITLE
Facebook Archive? should we expect this to be deprecated?

### ISSUE THREAD

**Issue by freak4pc** [facebookarchive/ios-snapshot-test-case#241]
It seems this repo has been moved to the facebookarchive org.
Are you expecting to deprecate this library ? Many of us still use it, so it would be a good to get a fair warning. 

Thank you :)

**Comment by krbarnes** [comment]
Maybe: https://github.com/facebookarchive/ios-snapshot-test-case/issues/227#issuecomment-335175385

**Comment by freak4pc** [comment]
That's a shame to hear.

**Comment by skyweb07** [comment]
Hey @freak4pc, because of this I've started a new project that aims do the same as `FBSnapshotTestCase`, if you want to take a look https://github.com/skyweb07/Snap.swift ;)

**Comment by Heckscheibe** [comment]
also here is another link, apparently Uber took over the project:
https://github.com/uber/ios-snapshot-test-case

**Comment by freak4pc** [comment]
Oh yeah, this is very old news by now :) I should've closed this a while ago.
